### ISSUE TITLE
Is there option for regression model

### ISSUE THREAD

**Issue by singsinghai** [amparore/leaf#1]
Dear Amparore,

I am a Bachelor's student researching on LIME. I came across your study about LEAF for LLC and am very interested in how LEAF offers a well-defined set of evaluation metrics.

I have read the code of this repo and have a question: Is your work mainly focused on Classifier, or does it work as well for Regression? Since the class name is `get_LIME_classifier`.

Also I want to mention that the source will only work for `sklearn` version < 1.2 due to the Ridge's attribute `normalize` is deprecated in version 1.2. You might want to update a environment requirements file for it.

I hope we can work on this to understand more about the potential of LEAF, and hope that my information on the package was helpful for you. I'm looking forward to your reply soon!
Thanks,
Hai

**Comment by amparore** [comment]
We were mostly focused on the classification task for LEAF, but the code in get_LIME_classifier and get_SHAP_classifier should work for regression models, since you are extracting in both cases a local linear classifier (i.e. the intercept and the coefficients returned in g).
If I remember correctly, only the Prescriptivity metric is restricted to the classification tasks - the others should in principle work for both classification and regression.

The interesting part of these two functions (get_LIME_classifier and get_SHAP_classifier) is that they will build comparable LLCs (at least comparable in the coefficients) for both LIME and SHAP - which is not trivial and require a delicate setup.

It could be that recent versions of sklearn have problems, since unfortunately the python ecosystem is not very API-stable. The Ridge regressor could probably be replaced with a simple LinearRegression model, since the alpha coefficient used was just 1.0. I believe I used the Ridge regressor just because I was replicating a similar code fragment of LIME.

**Comment by singsinghai** [comment]
Hi Amparore,

Thanks for the quick reply, I will try to test it on

**Comment by singsinghai** [comment]
Thanks for the quick reply, I will test it with a regression model to see if there is any problem.

Also some study shows that Ridge penalty is actually harmful for the ML surface of LIME, so I agree that using a simple Linear model will be fine.
